sudo: required
language: python
python:
  - "2.6"
  - "2.7"
services:
  - mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install python-mysqldb
  - sudo apt-get install python-dev libboost-python-dev python-pip
  - sudo apt-get install build-essential python-openssl
  - sudo pip install w1thermsensor
  - sudo pip install Flask
  - sudo pip install flask-httpauth
  
  - git clone git://git.drogon.net/wiringPi
  - cd wiringPi
  - ./build
  
  - cd ..
  - git clone https://github.com/lexruee/pi-switch-python.git
  - cd pi-switch-python
  - sudo python setup.py install

  #- cd ..
  #- git clone https://github.com/adafruit/Adafruit_Python_DHT.git
  #- cd Adafruit_Python_DHT
  #- sudo python setup.py install
script:
  - mysql -u root mysql < tests/database.sql
  - nosetests tests/UnitTest.py