sudo: required
language: python
python:
  - "2.6"
  - "2.7"
services:
  - mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev libboost-python-dev python-pip -y
  - sudo apt-get install build-essential python-openssl -y
  - sudo apt-get install libmysqlclient-dev -y
  #- pip install w1thermsensor
  - pip install Flask
  - pip install flask-httpauth
  - pip install MySQL-python
  
  #- git clone git://git.drogon.net/wiringPi
  #- cd wiringPi
  #- ./build
  
  #- pip install pi_switch
  #- cd ..
  #- git clone https://github.com/lexruee/pi-switch-python.git
  #- cd pi-switch-python
  #- sudo python setup.py install

  #- cd ..
  #- git clone https://github.com/adafruit/Adafruit_Python_DHT.git
  #- cd Adafruit_Python_DHT
  #- sudo python setup.py install
script:
  - cd $TRAVIS_BUILD_DIR/tests
  - mysql -u root mysql < database.sql
  - nosetests UnitTest.py