#!/bin/bash
# /etc/init.d/homeautomation

### BEGIN INIT INFO
# Provides:          homeautomation
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A Raspberry Pi home automation project
# Description:       A Raspberry Pi home automation project
### END INIT INFO


case "$1" in 
    start)
        echo "Starting Home-Automation"
        python /home/pi/Documents/home-automation/main.py &
        python /home/pi/Documents/home-automation/API.py &
        ;;
    stop)
        echo "Stopping Home-Automation"
	ps -ef | grep main.py | grep -v grep | awk '{print $2}' | xargs kill
	ps -ef | grep API.py | grep -v grep | awk '{print $2}' | xargs kill
        ;;
    *)
        echo "Usage: /etc/init.d/homeautomation start|stop"
        exit 1
        ;;
esac

exit 0